stages:
  prepare:
    cmd: python3 scr/prepare.py
    deps:
    - scr/prepare.py
    params:
    - prepare.categories
    outs:
    - data/prepared
  featurize:
    cmd: python3 scr/featurize.py data/prepared data/features
    deps:
    - data/prepared
    - scr/featurize.py
    outs:
    - data/features
  train:
    cmd: python3 scr/train.py data/features model.pkl
    deps:
    - data/features
    - scr/train.py
    params:
    - train.alpha
    outs:
    - model.pkl
  evaluate:
    cmd: python3 evaluate/evaluate.py model.pkl data/features score/scores.json score/plots.json
    deps:
    - data/features
    - model.pkl
    - evaluate/evaluate.py
    metrics:
    - score/scores.json:
        cache: false
    plots:
    - score/plots.json:
        cache: false
